# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8c292c746a6bb1cc85535cc5aaf86f4d771d42e8324ab8195f771467b8fa5d0f374849f80306970b46ab889e27ffaf9532c4cf66d06d3be8e18e7b6ab48ca36

test:
  secret_key_base: e467b14ce0339b585275ce475cd234fd5d013a9f331d39d64ca5767f267e527eee08c57b02f8e233275f2d7a74871ee14a87a8383531b59663618e15789078b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
